# Generated by Django 5.1.7 on 2025-03-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Terminated', 'Terminated')], default='Active', max_length=16),
        ),
    ]
